version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gamepicker-api
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
      - REDIS_CONNECTION_STRING=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    depends_on:
      - mongo
      - redis

volumes:
  mongo-data:
  redis-data: