services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=GamePicker;User Id=sa;Password=1StrongPwd!!;TrustServerCertificate=true;
      - REDIS_CONNECTION_STRING=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: [mssql, redis]

  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    hostname: mssql
    environment:
      - MSSQL_SA_PASSWORD=1StrongPwd!!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
